id: A170A7B6F
title: A Brief Prayer to the Precious Master PadmÄkara for Swiftly Fulfilling Wishes
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.476741
  last_modified_at: 2022-03-01 03:16:19.476749
