id: A170A7B6F
title: Prayer for Dispelling Famine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.486230
  last_modified_at: 2022-03-01 03:16:19.486233
