id: A170A7B6F
title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the Three
  Deities of Long Life'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.481297
  last_modified_at: 2022-03-01 03:16:19.481302
