id: A170A7B6F
title: Concise Seven-Heap Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.485159
  last_modified_at: 2022-03-01 03:16:19.485163
