id: A170A7B6F
title: An Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.482919
  last_modified_at: 2022-03-01 03:16:19.482922
