id: A170A7B6F
title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
  that Unites the Oral, Treasure and Visionary Teachings'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.490819
  last_modified_at: 2022-03-01 03:16:19.490822
