id: A170A7B6F
title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the Profound
  Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.484004
  last_modified_at: 2022-03-01 03:16:19.484006
