id: A170A7B6F
title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha Thangtong
  Gyalpo's Lifetime as Bhikṣu Padma Karpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.498234
  last_modified_at: 2022-03-01 03:16:19.498236
