id: A170A7B6F
title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the Fear
  of Disease'
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:16:19.496850
  last_modified_at: 2022-03-01 03:16:19.496853
